version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
          - ./application:/data

    # See https://hub.docker.com/_/postgres/ for details of the postgres image.
    # POSTGRES_PASSWORD - superuser password for PostgreSQL
    # POSTGRES_USER - superuser (default is 'postgres')
    # POSTGRES_DB - name of default database (default is value of POSTGRES_USER)
    db:
        image: postgres:9.6-alpine
        volumes_from:
            - data
        ports:
            - "5432"
        environment:
            POSTGRES_PASSWORD: r00tp@ss!

    adminer:
        image: adminer:4.6.3
        ports:
            - "8080:8080"

    # DB_HOST - hostname of the database server
    # DB_USER - user that accesses the database
    # DB_PASSWORD - password for the DB_USER
    # DB_NAMES - list of databases to back up/restore
    restore:
        build: ./
        volumes_from:
            - data
        env_file:
            - ./local.env
        environment:
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: r00tp@ss!
            DB_NAMES: world
            MODE: restore
            CRON_SCHEDULE: "25 * * * *"

    backup:
        build: ./
        volumes_from:
            - data
        env_file:
            - ./local.env
        environment:
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: r00tp@ss!
            DB_NAMES: world
            MODE: backup
            CRON_SCHEDULE: "20 * * * *"
